accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountDetailView, AccountUpdateView, AccountDeleteView
from accountapp.views import AccountCreateView

app_name = 'accountapp'
# "accountapp:hello_world""
urlpatterns = [
    #path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

inhoproj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),

    path('accounts/',  include('accountapp.urls')),
    path('profiles/',  include('profileapp.urls')),
    path('articles/',  include('articleapp.urls')),
    path('comments/',  include('commentapp.urls')),
    path('projects/',  include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.
class HelloWorld(models.Model):
#     id = models.IntegerField(default=1, primary_key=True)
#    id = models.AutoField(primary_key=True)
#    date = models.DateTimeField(auto_now_add=True)
#    text = models.CharField(max_length=256,null=False)
    text = models.CharField(max_length=255, null=False)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):

    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200,null=True)
    image = models.ImageField(upload_to= 'article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_created=True, null=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True;

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy

# Create your views here.
from django.utils.decorators import method_decorator
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from articleapp.models import Article
from inhoproj.settings.base import env

has_ownership = [login_required,account_ownership_required];

@login_required
def hello_world(request):
#    return HttpResponse('안녕하세요..')
    if request.user.is_authenticated:
        if request.method == "POST" :
            temp = request.POST.get('hello_world_input');

            new_hello_world = HelloWorld();
            new_hello_world.text = temp;
            new_hello_world.save();

            return HttpResponseRedirect(reverse('accountapp:hello_world'))
        else:
            hello_world_list = HelloWorld.objects.all()

            return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})
    else:
        return HttpResponseRedirect(reverse('accountapp:login'));


class AccountCreateView(CreateView) :
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:list')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView, MultipleObjectMixin) :
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    paginate_by = env('PAGE_PER')

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)

# @method_decorator(login_required,'get')
# @method_decorator(login_required,'post')
# @method_decorator(account_ownership_required,'get')
# @method_decorator(account_ownership_required,'post')
@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class AccountUpdateView(UpdateView) :
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'

    # def get(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().get(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()
    #
    # def post(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().post(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()


@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class AccountDeleteView(DeleteView, MultipleObjectMixin) :
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

    # def get(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().get(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()
    #
    # def post(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().post(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4> SignUp </h4>
        </div>
        <form action="{% url 'accountapp:create' %}" method="post">
           {% csrf_token %}
<!--           {{ form }}-->
           {% bootstrap_form form %}
           <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>

    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto">
<!--            <p> {{ target_user.date_joined }} </p>-->
            {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt="우리아이들"
                 style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom:2rem; object-fit:cover">
            <h2 style="font-family: 'NanumSquareB'">
                {{ target_user.profile.nickname }}
                {% if target_user == user %}
                <a class="material-icons"
                   style="box-shadow:0 0 3px #ccc; border-radius: 10rem; padding: .4rem"
                    href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                      edit
                </a>
                {% endif %}
            </h2>
            <h5 style="margin-bottom:3rem">
                {{ target_user.profile.message }}
            </h5>
            {% else %}
                {% if target_user == user %}
                <a href="{% url 'profileapp:create' %}">
                    <h2 style="font-family: 'NanumSquareB'">프로필</h2>
                </a>
                {% else %}
                <h3> 프로파일 등록요망...</h3>
                {% endif %}
            {% endif %}

<!--            <h2 style="font-family: 'NanumSquareB'">-->
<!--                {{ target_user.username }}-->
<!--            </h2>-->
            {% if target_user == user %}
            <a class="material-icons"
               style="box-shadow:0 0 3px #ccc; border-radius: 10rem; padding: .4rem"
               href="{% url 'accountapp:update' pk=target_user.pk %}">
                 settings
            </a>
            <a class="material-icons"
               style="box-shadow:0 0 3px #fcc; border-radius: 10rem; padding: .4rem"
               href="{% url 'accountapp:delete' pk=target_user.pk %}">
                cancel
            </a>
            {% endif %}
        </div>
   </div>
    <div>
      {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center">

        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %}
            <div>
               <input type="text" name="hello_world_input">
            </div>
            <div>
               <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>
        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
            <h4>
                {{ hello_world.text }}
            </h4>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4> Login </h4>
        </div>
        <div>
            <form action="" method="post">
               {% csrf_token %}
<!--               {{ form }}-->
               {% bootstrap_form form %}
               <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4> SignUp </h4>
        </div>
        <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
           {% csrf_token %}
           {% bootstrap_form form %}
           <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>

    </div>

{% endblock %}